enum Screens {
  MAIN_APP = 'MAIN_APP',
  MENU = 'MENU',
  BASKET = 'BASKET',
  BASKET_SUCCESS = 'BASKET_SUCCESS',
  BROADCAST = 'BROADCAST',
  CONTACTS = 'CONTACTS',
  RESERVE = 'RESERVE',
  RESERVE_SUCCESS = 'RESERVE_SUCCESS',
  EVENTS = 'EVENTS',
  EVENTS_DETAIL = 'EVENTS_DETAIL',
}

export default Screens;
